AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - Gemfile
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/acceptance/acceptance_helper.rb'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'app/indices/*'        
  DisplayCopNames: true


# > Limit lines to 80 characters.
# How did we get here?
# Github's code views fit 101 character without horizontal scrolling
Layout/LineLength:
  Max: 101

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

