require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "spec/acceptance/acceptance_helper.rb"
    - "tmp/**/*"
    - "public/**/*"
    - "app/indices/*"
    - "node_modules/**/*"
  DisplayCopNames: true

Layout/LineLength:
  Max: 101

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false