version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/web/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      command: ./docker_dev/docker-entrypoint.sh
  database:
    image: postgres:12.11
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "password"
  redis:
    image: redis:5.0.7
    # volumes:
      # - redisdata:/data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
      - database
      - redis
    volumes:
      - .:/web
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/web/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./docker-dev/sidekiq-entrypoint.sh
volumes:
  gem_cache:
  db_data:
  node_modules:
  # redisdata:
  #   driver: local
